# -*- coding: utf-8 -*-
"""coloring.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y6n-vK7_8hIsyf7TbaVdGOo4Qo51LJxr
"""

import tensorflow as tf
from tensorflow import keras
from keras.models import load_model
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
from PIL import Image
from skimage.color import rgb2gray
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from keras.models import Model, load_model,Sequential
from keras.preprocessing.image import ImageDataGenerator
from keras.layers import Input, Dense, UpSampling2D, RepeatVector, Reshape
from keras.layers.core import Dropout, Lambda
from keras.layers.convolutional import Conv2D, Conv2DTranspose
from keras.layers.pooling import MaxPooling2D
from keras.layers.merge import concatenate
from keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau

import os
import zipfile

local_zip = '/content/drive/My Drive/crop_part1.zip'
zip_ref = zipfile.ZipFile(local_zip, 'r')
zip_ref.extractall('/tmp/data')
zip_ref.close()

trainIm = os.listdir('/tmp/data/crop_part1')
print(trainIm[:10])
print('total training images:', len(os.listdir('/tmp/data/crop_part1')))
print('total training images:', (trainIm[1] ))

data=[]
datagray=[]
dataTest=[]
dataGrayTest=[]
nIm=5000
dirs=os.listdir('/tmp/data/crop_part1')
img_Bdir='/tmp/data/crop_part1/'
i=0
for name in dirs:

  if name != 'Untitled.m' and name != 'resizing.m' and name != 'myImage.jpg' and name != 'ss.jpg' and i<nIm : 
    img_dir= img_Bdir  + name
    img = plt.imread(img_dir)
    datagray.append(rgb2gray(img))
    data.append(img)
  if name != 'Untitled.m' and name != 'resizing.m' and name != 'myImage.jpg' and name != 'ss.jpg' and i>nIm :
    img_dir= img_Bdir  + name
    img = plt.imread(img_dir)
    dataGrayTest.append(rgb2gray(img))
    dataTest.append(img)
  i=i+1

data=np.array(data)
data=data/255
datagray=np.array(datagray)
datagray=datagray/255
dataTest=np.array(dataTest)
dataTest=dataTest/255
dataGrayTest=np.array(dataGrayTest)
dataGrayTest=dataGrayTest/255

print(data[1].shape)
print(data.shape)
print(datagray[1].shape)
datagray= np.reshape(datagray,(nIm-4 ,200,200,1))
dataGrayTest= np.reshape(dataGrayTest,(6867-nIm ,200,200,1))
print(datagray.shape)
print(dataTest[1].shape)
print(dataTest.shape)
print(dataGrayTest[1].shape)
print(dataGrayTest.shape)

# Define the model
# Use no more than 2 Conv2D and 2 MaxPooling2D
model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(128, (3,3), activation='relu',padding='same',strides=1 , input_shape=(200, 200,1)),
    tf.keras.layers.MaxPool2D((2, 2), padding='same'),
    tf.keras.layers.Conv2D(128, (4,4), activation='relu', padding='same'),
    tf.keras.layers. Conv2D(128, (3,3), activation='relu', padding='same',strides=1),
    tf.keras.layers.MaxPool2D((2, 2), padding='same'),
    tf.keras.layers.Conv2D(256, (4,4), activation='relu', padding='same'),
    tf.keras.layers.Conv2D(256, (3,3), activation='relu', padding='same',strides=1),
    tf.keras.layers.MaxPool2D((2, 2), padding='same'),
    tf.keras.layers.Conv2D(256, (4,4), activation='relu', padding='same'),
    tf.keras.layers.Conv2D(256, (3,3), activation='relu', padding='same'),
    tf.keras.layers.Conv2D(256, (3,3), activation='relu', padding='same'),

    tf.keras.layers.Conv2D(128, (3,3), activation='relu', padding='same'),
    tf.keras.layers.Conv2D(64, (3,3), activation='relu', padding='same'),
    tf.keras.layers.UpSampling2D((2, 2)),
    tf.keras.layers.Conv2D(128, (3,3), activation='relu', padding='same'),
    tf.keras.layers.UpSampling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (4,4), activation='relu', padding='same'),
    tf.keras.layers.Conv2D(64, (3,3), activation='relu', padding='same'),
    tf.keras.layers.Conv2D(32, (2,2), activation='relu', padding='same'),
    tf.keras.layers.Conv2D(3, (3,3), activation='tanh', padding='same'),
    tf.keras.layers.UpSampling2D((2, 2))
     ])
adam=keras.optimizers.Adam() 
# Compile Model. 
history=model.compile(loss='mse', optimizer=adam, metrics=['accuracy'])
model.summary()

model = tf.keras.models.load_model('/content/drive/My Drive/bestmodel03.h5')

for i in range(100):  
  model.fit(datagray,data, epochs=50, batch_size=120,shuffle=True )
  model.save('/content/drive/My Drive/bestmodel03.h5')

model.save('/content/drive/My Drive/bestmodel03.h5')

a=1050
pred = model.predict(dataGrayTest)
GrayTest=np.reshape(dataGrayTest,(6867-nIm,200,200))
for i in range (40):
    
  plt.figure(figsize=(4,4))
  plt.subplot(221)
  plt.imshow(GrayTest[a+i], cmap="gray")
  
  plt.subplot(223)
  plt.imshow(dataTest[a+i])
  #plt.tilte('Autoencoder Input')
  
  plt.subplot(222)
  img = pred[a+i].reshape(200,200,3)
  plt.imshow(img)
  plt.show()
  #plt.title('Autoencoder Outer ')

plt.show()

def getPredictByIndex(index):
  pred = model.predict(dataGrayTest)
  img_array2 = pred[index].reshape(200,200,3)
  img_array2 = (img_array2*255.0)
  img_array2 = img_array2.astype(np.uint8)
  return Image.fromarray(img_array2, 'RGB')